[package]
name = "pyth-prices"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3.3", features = ["full"] }
eyre = "0.6.12"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "net", "rt-multi-thread", "macros"] }